### ISSUE TITLE
首页下载简历失败问题

### ISSUE THREAD

**Issue by wanglihuaya** [Codefreyy/joy-personal-portfolio#2]
#### 首页下载简历失败问题

环境：chrome 中文

看了下代码，本来想提pr的，发现是没有中文版本的简历的资源的问题，就来提issue

<img width="320" alt="image" src="https://github.com/user-attachments/assets/a9847427-eb48-41e7-a0bb-17ff2876af44">

> 是从B站过来的，up主的网站很漂亮，简历也很优秀，技术也很棒 👍

**Comment by Codefreyy** [comment]
> #### 首页下载简历失败问题
> 
> 环境：chrome 中文
> 
> 看了下代码，本来想提pr的，发现是没有中文版本的简历的资源的问题，就来提issue
> <img alt="image" width="320" src="https://private-user-images.githubusercontent.com/49522285/359755216-a9847427-eb48-41e7-a0bb-17ff2876af44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDI0NDMsIm5iZiI6MTcyNDg0MjE0MywicGF0aCI6Ii80OTUyMjI4NS8zNTk3NTUyMTYtYTk4NDc0MjctZWI0OC00MWU3LWEwYmItMTdmZjI4NzZhZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYTgwMzc3ZjhmOWNkMjQ0ZjI5ODVhNGI2Yjk5M2Y1ZTc5MjY0Y2M1NWQyNGVkOTlkMjg3NDkwZjQxMDdlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7RqpDTDN6-Pw2rJVhTFo38OrW2QTqJhLW2nNp2QFPo">
> 
> > 是从B站过来的，up主的网站很漂亮，简历也很优秀，技术也很棒 👍

谢谢指出！我已经加上了中文简历～～
